name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]
       
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure --prefix=$(pwd)/build

    - name: make
      run: make

    - name: test
      run: make test

    - name: install
      run: make install
