name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]
       
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Installation (MacOS)
      run: brew install automake
      if: matrix.os == 'macos-latest'

    - name: autoreconf
      run: autoreconf -i
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

    - name: configure
      run: bash "./configure" --prefix=$(pwd)\build

    - name: make
      run: make

    - name: install
      run: make install
