name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]
       
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
      
    - name: configure
      run: ./configure --prefix=$(pwd)/build

    - name: make
      run: make
    
    - name: Change branch
      run: git pull --all && git switch workflow
      
    - name: Copy release
      run: "sudo cp $(pwd)/build/bin/blaze /tmp/blaze"
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      
    - name: Move release
      run: "sudo mv /tmp/blaze $GITHUB_WORKSPACE/blaze-${{ matrix.os }}"
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      
    - name: Commit
      run: |
        (git config --global user.name 'GitHub Actions' &&
        git config --global user.email 'virtual-designer@users.noreply.github.com' &&
        git add blaze-* &&
        git commit -m "Automated Build Workflow Commit" &&
        git push origin workflow --force) || echo 0
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      
    - name: Commit
      run: |
        (ls && rm ./blaze-windows && mv $(pwd)/build/bin/blaze.exe ./blaze-windows && git config --global user.name 'GitHub Actions' &&
        git config --global user.email 'virtual-designer@users.noreply.github.com' &&
        git add ./blaze-windows &&
        git commit -a -m "Automated Build Workflow Commit" &&
        git push origin workflow --force) || echo 0
      if: matrix.os == 'windows-latest'
